### PR TITLE
Controllers specs

### PR DESCRIPTION
**Pull request by Chaseknis**
- Create a Request spec file for all controllers
- Add posts_spec.rb and users_spec.rb
- Add RSpec as a gem to the project
- Run linters for errors
- For each action you check:

- [x] If response status was correct.
- [x] If a correct template was rendered.
- [x] If the response body includes correct placeholder text.

### CODE REVIEW

**Review by TadesseDev — APPROVED** [review]
### Hi @Chaseknis 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)



## Highlights
 - [x]  Correct GitHub Flow. ✅
 - [x]  Good PR title/description. ✅
 - [x]  All linters passed ✅
## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chaseknis** [comment]
@TadesseDev Thank you1

**Comment by TadesseDev** [comment]
You did a great job @Chaseknis 🙌

**Comment by Chaseknis** [comment]
@TadesseDev my dashboard is still showing REVIEW PENDING, is there something wrong?

**Pull request merged**
